name: PHAR build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"

      - shell: bash
        run: cp psh.phar .github

      - name: execute example scripts
        run: |
          .github/psh.phar
          .github/psh.phar test
          .github/psh.phar test-env --env=ci
